name: Check SPARQL queries
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:

  check:
    name: Run SPARQL checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install tester
      run: wget 'https://github.com/sib-swiss/sparql-examples-utils/releases/download/v1.0.0/sparql-examples-util-1.0.0-uber.jar' -O sparql-util.jar

    - name: Run tests
      run: java -cp sparql-util.jar swiss.sib.rdf.sparql.examples.Tester --input-directory=examples/
